/* tslint:disable */
/* eslint-disable */
// This file was automatically generated and should not be edited.

//==============================================================
// START Enums and Input Objects
//==============================================================

export enum PostStatus {
  private = "private",
  public = "public",
}

/**
 * Autogenerated input type of CreateAdmin
 */
export interface CreateAdminInput {
  clientMutationId?: string | null;
  email: string;
  password: string;
}

/**
 * Autogenerated input type of CreateCategory
 */
export interface CreateCategoryInput {
  clientMutationId?: string | null;
  name: string;
}

/**
 * Autogenerated input type of CreatePost
 */
export interface CreatePostInput {
  clientMutationId?: string | null;
  categoryId: string;
  authorName?: string | null;
  email?: string | null;
  title?: string | null;
  body: string;
}

/**
 * Autogenerated input type of DeleteCategory
 */
export interface DeleteCategoryInput {
  clientMutationId?: string | null;
  id: string;
}

/**
 * Autogenerated input type of UpdateCategory
 */
export interface UpdateCategoryInput {
  clientMutationId?: string | null;
  id: string;
  name: string;
}

/**
 * Autogenerated input type of UpdatePost
 */
export interface UpdatePostInput {
  clientMutationId?: string | null;
  id: string;
  status: PostStatus;
}

//==============================================================
// END Enums and Input Objects
//==============================================================
